### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by carobro** [carobro/Geosoftware2#74]
- [ ] **CLI** 
   - [x] `Shapefile` fehler korrigieren 
   - [x] Ordnerfehler abfangen falls kein CRS vorhanden ist 
   - [x] `Similarity` Funktion korrigieren 
   - [x] `folder` Parameter löschen 
   - [x] Abfangen, dass von Ordner keine ConexHull berechnet werden kann
   - [ ] GML Korrigieren
   - [x] `umstrukturierungs` Branch auf Master setzen  
   - [x] Aktuelles **PyPi** Modul hochladen 

- [ ] **API** 
   - [x] Geodaten in GeoJson kodiert
   - [x] api/records/[ID]/similar?size=[n] Parameter
   - [x] getMetadata fuer mehrere Dateien moeglich machen
   - [x] Tests schreiben 
   - [x] Geeignete Testdaten für Demo auf Zenodo hochladen
- [ ] **Docker** 
   - [ ] extracttool 0.4.8 has requirement Click==7.0, but you'll have click 6.7 which is incompatible
   - [ ] extracttool 0.4.8 has requirement pytest==3.3.2, but you'll have pytest 4.1.1 which is incompatible
   - [ ] Image erstellen, Auf Docker Hub laden
- [ ] **Doku etc** ReadMe, Doku für von Docker laden, Präsi, Dateien die wir zeigen wollen
- [ ] **Issues** schließen
- [x] **Kommentierung** überprüfen

**Comment by JaFro96** [comment]
Das neue GitKraken hat mir das heute angezeigt bei den ToDos. 😄 
Ich glaube hier machen wir nicht mehr und schließe das mal.
Viele Grüße

**Comment by carobro** [comment]
Schade, dachte vielleicht wird sich dem noch jemand annehmen 😂
Viele Grüsse zurück
